### PR TITLE
Add findcommandfilters

### PR DESCRIPTION
**Pull request by 000verflow**

### CODE REVIEW

**Comment by yingx9** [comment]
My getReceivedDate again...run the ./runtest.bat and replace the EXPECTED.txt with the results should pass the checks 

Its cause its gets the current System date...Maybe I should change that lol

**Comment by 000verflow** [comment]
I did copy the ACTUAL.txt, but may the github's server wasn't in the same timezone as us, so it failed on the github side.

**Comment by 000verflow** [comment]
Yea my hypothesis was right, I rerun now and it works.

**Comment by yingx9** [comment]
Ok, no issues now!

**Pull request merged**
